### ISSUE TITLE
nc_Figure2

### ISSUE THREAD

**Issue by shmp0722** [jyeatman/lifespan#1]
Hi Jason

Loading example fibers part has a path issue.

Adding  fullpath to the example file

% Load example fibers and fiber group names
exampleFg = fullfile(nc_Path,'data','exampleSubject/exampleFibers.mat');
load(exampleFg)

or changing directory before loading example fibers

% Change to directory with example data
cd(fullfile(nc_Path,'data','exampleSubject'))

will work.

SO

**Comment by jyeatman** [comment]
Thanks for the catch. This was working for me because I had added the whole lifespan directory to my search path. Now I added your general fix.
